CREATE TABLE MutualFunds
(
    FundId INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_Fund_Id PRIMARY KEY,
    AmcId INT NOT NULL,
    FundName NVARCHAR(500) NOT NULL,
    Category INT NULL,
    ISIN NVARCHAR(200) NULL,
    IsActive BIT NOT NULL DEFAULT (1),

    CONSTRAINT FK_MutualFunds_AMCs 
        FOREIGN KEY (AmcId) REFERENCES AMCs(AmcId)
);