CREATE TABLE MutualFundNAVHistory
(
    FundId INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    NavDate DATETIME NOT NULL,
    NAV DECIMAL(10,2) NOT NULL,
    CreatedDate DATETIME NOT NULL DEFAULT (GETDATE()),
    ModifiedDate DATETIME NULL,
);